# Generated by Django 6.0 on 2025-12-06 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_expiracao', models.DateField(verbose_name='Data de Expiração')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(verbose_name='Fim')),
                ('em_andamento', models.BooleanField(default=False, verbose_name='Em Andamento')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('realizacoes', models.JSONField(default=list, verbose_name='Realizações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('nivel', models.CharField(choices=[('TECNICO', 'Técnico'), ('BACHARELADO', 'Bacharelado'), ('LICENCIATURA', 'Licenciatura'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=20, verbose_name='Nível')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(verbose_name='Fim')),
                ('em_andamento', models.BooleanField(default=False, verbose_name='Em Andamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('nivel', models.CharField(choices=[('INICIANTE', 'Iniciante'), ('INTERMEDIARIO', 'Intermediário'), ('AVANCADO', 'Avançado')], max_length=20, verbose_name='Nível')),
                ('anos_de_experiencia', models.PositiveIntegerField(verbose_name='Anos de Experiência')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('link', models.URLField(verbose_name='Link')),
                ('habilidades', models.ManyToManyField(to='curriculos.habilidade', verbose_name='Habilidades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
